import fs from 'node:fs';
import path from 'node:path';

/**
 * Vite plugin that discovers and bundles frontend assets from Laravel Slice modules.
 *
 * This plugin works in two modes:
 *
 * 1. **Manifest mode** (recommended for production): Reads a manifest JSON file
 *    generated by `php artisan slice-assets:discover`. This is the most reliable
 *    approach since the PHP side knows exactly which slices are registered.
 *
 * 2. **Directory scanning mode** (convenient for development): Scans a directory
 *    for slice subdirectories and looks for entry point files in each.
 *
 * The plugin adds discovered entry points to Vite's rollup input configuration,
 * so they are included in the build output alongside your main app assets.
 *
 * It also creates import aliases for each slice, so you can reference slice
 * assets cleanly in your code:
 *
 *   import { something } from '@slice:blog/components/Widget.vue'
 *
 * @param {SliceAssetsOptions} options
 * @returns {import('vite').Plugin}
 *
 * @example
 * // vite.config.js
 * import laravel from 'laravel-vite-plugin';
 * import sliceAssets from 'vite-plugin-slice-assets';
 *
 * export default defineConfig({
 *   plugins: [
 *     laravel({
 *       input: ['resources/css/app.css', 'resources/js/app.js'],
 *     }),
 *     sliceAssets({
 *       // Option A: Use the manifest (run `php artisan slice-assets:discover` first)
 *       manifestPath: 'bootstrap/cache/slice-assets.json',
 *
 *       // Option B: Scan directories directly (no manifest needed)
 *       // slicesDirectory: 'slices',
 *       // entryPoints: ['resources/js/app.js', 'resources/js/app.ts', 'resources/css/app.css'],
 *     }),
 *   ],
 * });
 */

/**
 * @typedef {Object} SliceAssetsOptions
 *
 * @property {string} [manifestPath='bootstrap/cache/slice-assets.json']
 *   Path to the manifest file generated by `php artisan slice-assets:discover`.
 *   Relative to the project root.
 *
 * @property {string} [slicesDirectory]
 *   Path to the directory containing slice subdirectories.
 *   When set, the plugin scans this directory instead of reading the manifest.
 *   Relative to the project root. Example: 'slices'
 *
 * @property {string[]} [entryPoints=['resources/js/app.js', 'resources/js/app.ts', 'resources/css/app.css']]
 *   Entry point file paths to look for in each slice (relative to slice root).
 *   Only used in directory scanning mode.
 *
 * @property {string} [assetsDirectory='resources']
 *   The assets directory name within each slice. Used for creating aliases.
 *
 * @property {string} [aliasPrefix='@slice:']
 *   Prefix for import aliases. E.g. '@slice:blog' resolves to the blog slice's
 *   assets directory.
 */

/**
 * @param {SliceAssetsOptions} options
 * @returns {import('vite').Plugin}
 */
export default function sliceAssets(options = {}) {
    const {
        manifestPath = 'bootstrap/cache/slice-assets.json',
        slicesDirectory = null,
        entryPoints = [
            'resources/js/app.js',
            'resources/js/app.ts',
            'resources/css/app.css',
        ],
        assetsDirectory = 'resources',
        aliasPrefix = '@slice:',
    } = options;

    /** @type {Map<string, string[]>} slice name => entry points */
    let discoveredSlices = new Map();

    /**
     * Discover slices from the manifest file.
     * @param {string} projectRoot
     * @returns {Map<string, string[]>}
     */
    function discoverFromManifest(projectRoot) {
        const fullPath = path.resolve(projectRoot, manifestPath);
        const slices = new Map();

        if (!fs.existsSync(fullPath)) {
            console.warn(
                `[slice-assets] Manifest not found at ${fullPath}. ` +
                `Run 'php artisan slice-assets:discover' to generate it.`
            );
            return slices;
        }

        try {
            const manifest = JSON.parse(fs.readFileSync(fullPath, 'utf-8'));

            for (const [sliceName, sliceEntryPoints] of Object.entries(manifest.slices || {})) {
                slices.set(sliceName, sliceEntryPoints);
            }
        } catch (err) {
            console.error(`[slice-assets] Failed to parse manifest: ${err.message}`);
        }

        return slices;
    }

    /**
     * Discover slices by scanning the filesystem.
     * @param {string} projectRoot
     * @returns {Map<string, string[]>}
     */
    function discoverFromDirectory(projectRoot) {
        const slices = new Map();
        const fullDir = path.resolve(projectRoot, slicesDirectory);

        if (!fs.existsSync(fullDir)) {
            console.warn(`[slice-assets] Slices directory not found: ${fullDir}`);
            return slices;
        }

        // Recursively find slice directories that contain asset entry points
        scanSliceDirectory(fullDir, '', projectRoot, slices);

        return slices;
    }

    /**
     * Recursively scan for slices. A directory is considered a slice if it
     * contains any of the configured entry point files.
     *
     * This supports nested slices: slices/api/posts/ becomes slice "api.posts".
     *
     * @param {string} dir  Current directory to scan
     * @param {string} prefix  Dot-separated prefix for nested slice names
     * @param {string} projectRoot
     * @param {Map<string, string[]>} slices
     */
    function scanSliceDirectory(dir, prefix, projectRoot, slices) {
        const entries = fs.readdirSync(dir, { withFileTypes: true });

        for (const entry of entries) {
            if (!entry.isDirectory()) continue;

            const sliceDir = path.join(dir, entry.name);
            const sliceName = prefix ? `${prefix}.${entry.name}` : entry.name;

            // Check if this directory has any entry point files
            const found = [];

            for (const ep of entryPoints) {
                const epPath = path.join(sliceDir, ep);

                if (fs.existsSync(epPath)) {
                    // Store path relative to project root (forward slashes for Vite)
                    found.push(path.relative(projectRoot, epPath).replace(/\\/g, '/'));
                }
            }

            if (found.length > 0) {
                slices.set(sliceName, found);
            }

            // Continue scanning for nested slices
            scanSliceDirectory(sliceDir, sliceName, projectRoot, slices);
        }
    }

    return {
        name: 'vite-plugin-slice-assets',

        /**
         * Runs during config resolution. Discovers slice assets and:
         * 1. Adds their entry points to rollup's input configuration
         * 2. Sets up import aliases for each slice
         */
        config(config, { command }) {
            const projectRoot = config.root || process.cwd();

            // Discover slices using the appropriate mode
            discoveredSlices = slicesDirectory
                ? discoverFromDirectory(projectRoot)
                : discoverFromManifest(projectRoot);

            if (discoveredSlices.size === 0) {
                return;
            }

            // Collect all entry points
            const allEntryPoints = {};

            for (const [sliceName, eps] of discoveredSlices) {
                for (const ep of eps) {
                    // Create a descriptive input name: "slice:blog/js/app"
                    const ext = path.extname(ep);
                    const name = ep.replace(ext, '');
                    allEntryPoints[`slice:${sliceName}/${path.basename(ep, ext)}`] = path.resolve(projectRoot, ep);
                }
            }

            // Build aliases for clean imports: @slice:blog -> slices/blog/resources
            const aliases = [];

            for (const [sliceName, eps] of discoveredSlices) {
                if (eps.length > 0) {
                    // Derive the slice assets directory from the first entry point
                    const firstEp = eps[0];
                    const assetsIdx = firstEp.indexOf(`/${assetsDirectory}/`);

                    if (assetsIdx !== -1) {
                        const sliceAssetsDir = firstEp.substring(0, assetsIdx + assetsDirectory.length + 1);

                        aliases.push({
                            find: `${aliasPrefix}${sliceName}`,
                            replacement: path.resolve(projectRoot, sliceAssetsDir),
                        });
                    }
                }
            }

            // Log what was discovered
            const totalEntryPoints = Object.keys(allEntryPoints).length;
            console.log(
                `[slice-assets] Discovered ${totalEntryPoints} entry point(s) ` +
                `across ${discoveredSlices.size} slice(s)`
            );

            return {
                resolve: {
                    alias: aliases,
                },
                build: {
                    rollupOptions: {
                        input: allEntryPoints,
                    },
                },
            };
        },

        /**
         * During dev, watch slice asset directories for changes.
         * This ensures HMR picks up new files added to slices.
         */
        configureServer(server) {
            for (const [sliceName, eps] of discoveredSlices) {
                for (const ep of eps) {
                    const dir = path.dirname(path.resolve(server.config.root, ep));
                    server.watcher.add(dir);
                }
            }
        },
    };
}
