import type { Plugin } from 'vite';

export interface SliceAssetsOptions {
    /**
     * Path to the manifest file generated by `php artisan slice-assets:discover`.
     * Relative to the project root.
     * @default 'bootstrap/cache/slice-assets.json'
     */
    manifestPath?: string;

    /**
     * Path to the directory containing slice subdirectories.
     * When set, the plugin scans this directory instead of reading the manifest.
     * Relative to the project root. Example: 'slices'
     */
    slicesDirectory?: string;

    /**
     * Entry point file paths to look for in each slice (relative to slice root).
     * Only used in directory scanning mode.
     * @default ['resources/js/app.js', 'resources/js/app.ts', 'resources/css/app.css']
     */
    entryPoints?: string[];

    /**
     * The assets directory name within each slice. Used for creating aliases.
     * @default 'resources'
     */
    assetsDirectory?: string;

    /**
     * Prefix for import aliases.
     * E.g. '@slice:blog' resolves to the blog slice's assets directory.
     * @default '@slice:'
     */
    aliasPrefix?: string;
}

/**
 * Vite plugin that discovers and bundles frontend assets from Laravel Slice modules.
 */
export default function sliceAssets(options?: SliceAssetsOptions): Plugin;
